### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by toxic-johann** [toxic-johann/webpack-cdn-upload-plugin#1]
- [x] chunk uploader
- [x] async chunk rename
- [x] async chunk rename with uglifyjs
- [x] partial async chunk rename
- [x] chunk rename with html-webpack-plugin
- [x] css chunk rename with html-webpack-plugin and extract-text-webpack-plugin
- [x] rename image include by file-loader in css
- [x] ~~rename image include by html-loader in html~~
- [x] preload-webpack-plugin
- [x] manifest generate
- [x] logger
